version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: talentai-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talent_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - talentai-network

  ollama:
    image: ollama/ollama:latest
    container_name: talentai-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - talentai-network

  backend:
    build: .
    container_name: talentai-backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/talent_ai
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_AI_OLLAMA_BASE_URL: http://ollama:11434
      SPRING_AI_OLLAMA_CHAT_MODEL: llama3
    depends_on:
      - postgres
      - ollama
    networks:
      - talentai-network

  frontend:
    build: ./frontend
    container_name: talentai-frontend
    ports:
      - "3000:3000"
    environment:
      - CI=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    networks:
      - talentai-network

  prometheus:
    image: prom/prometheus:latest
    container_name: talentai-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - talentai-network

  grafana:
    image: grafana/grafana:latest
    container_name: talentai-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - talentai-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-tp
    privileged: true
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - talentai-network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube-tp
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db-sonar:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db-sonar
    networks:
      - talentai-network

  db-sonar:
    image: postgres:16
    container_name: postgres-sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_sonar_data:/var/lib/postgresql/data
    networks:
      - talentai-network

volumes:
  postgres_data:
  ollama_data:
  jenkins_home:
  postgres_sonar_data:

networks:
  talentai-network:
    driver: bridge